// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: guest.proto

// guest.proto defines the guest-side transport between weft-init
// (PID 1 inside an openweft micro-VM) and weft-agent (running on
// the hypervisor host).
//
// Two services live here:
//
//   * `GuestPodPlane` — what the guest dials on the host side.
//     The host listens on AF_VSOCK ; the guest opens a long-lived
//     bidirectional stream and reports pod / container events,
//     log chunks, and replies to control requests the host injects.
//
//   * `PodLifecycle` (future, not yet wired) — what the operator-
//     facing weft-agent surfaces upward to the control plane to
//     drive pod creation / mutation. Kept here so the type system
//     for PodSpec stays single-sourced.
//
// Mirrors agent.proto's split: machine-to-machine RPCs live in
// their own file with their own auth boundary (vsock identity is
// implicit — the guest's CID identifies the VM, the host enforces
// per-VM access policy in weft-agent before responding).
//
// See [[openweft-module-layout]] for placement.

package guestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartPolicy int32

const (
	RestartPolicy_RESTART_NEVER      RestartPolicy = 0
	RestartPolicy_RESTART_ON_FAILURE RestartPolicy = 1
	RestartPolicy_RESTART_ALWAYS     RestartPolicy = 2
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_NEVER",
		1: "RESTART_ON_FAILURE",
		2: "RESTART_ALWAYS",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_NEVER":      0,
		"RESTART_ON_FAILURE": 1,
		"RESTART_ALWAYS":     2,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_proto_enumTypes[0].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_guest_proto_enumTypes[0]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{0}
}

type Stream int32

const (
	Stream_STREAM_UNSPECIFIED Stream = 0
	Stream_STREAM_STDOUT      Stream = 1
	Stream_STREAM_STDERR      Stream = 2
)

// Enum value maps for Stream.
var (
	Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STREAM_STDOUT",
		2: "STREAM_STDERR",
	}
	Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STREAM_STDOUT":      1,
		"STREAM_STDERR":      2,
	}
)

func (x Stream) Enum() *Stream {
	p := new(Stream)
	*p = x
	return p
}

func (x Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_proto_enumTypes[1].Descriptor()
}

func (Stream) Type() protoreflect.EnumType {
	return &file_guest_proto_enumTypes[1]
}

func (x Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stream.Descriptor instead.
func (Stream) EnumDescriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{1}
}

type PodSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodId         string                 `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Containers    []*Container           `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Shares        []*Share               `protobuf:"bytes,3,rep,name=shares,proto3" json:"shares,omitempty"`
	Network       *Network               `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Wireguard     *WireGuard             `protobuf:"bytes,6,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	ShareMounts   []*ShareMount          `protobuf:"bytes,7,rep,name=share_mounts,json=shareMounts,proto3" json:"share_mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{0}
}

func (x *PodSpec) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *PodSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodSpec) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *PodSpec) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *PodSpec) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PodSpec) GetWireguard() *WireGuard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *PodSpec) GetShareMounts() []*ShareMount {
	if x != nil {
		return x.ShareMounts
	}
	return nil
}

// ShareMount is one multi-attach POSIX share (CubeFS-backed) mounted in
// the guest. Doubles as the dynamic mount/unmount payload an operator
// publishes on the event bus. Mirrors weft-microvm-init/pkg/pod.ShareMount.
// (Note: the dynamic path travels as JSON on NATS, not protobuf; this
// message keeps the on-wire PodSpec a faithful mirror for GuestHelloAck.)
type ShareMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // "" / "mount" | "unmount"
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"` // "cubefs" (default)
	MountPoint    string                 `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Readonly      bool                   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Cubefs        *CubeFSMount           `protobuf:"bytes,6,opt,name=cubefs,proto3" json:"cubefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareMount) Reset() {
	*x = ShareMount{}
	mi := &file_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareMount) ProtoMessage() {}

func (x *ShareMount) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareMount.ProtoReflect.Descriptor instead.
func (*ShareMount) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ShareMount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShareMount) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ShareMount) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ShareMount) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *ShareMount) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *ShareMount) GetCubefs() *CubeFSMount {
	if x != nil {
		return x.Cubefs
	}
	return nil
}

// CubeFSMount is the CubeFS connection detail the in-guest cfs-client needs.
type CubeFSMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Masters       []string               `protobuf:"bytes,2,rep,name=masters,proto3" json:"masters,omitempty"` // master node "host:port" list
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	AccessKey     string                 `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Subdir        string                 `protobuf:"bytes,6,opt,name=subdir,proto3" json:"subdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubeFSMount) Reset() {
	*x = CubeFSMount{}
	mi := &file_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeFSMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeFSMount) ProtoMessage() {}

func (x *CubeFSMount) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeFSMount.ProtoReflect.Descriptor instead.
func (*CubeFSMount) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{2}
}

func (x *CubeFSMount) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *CubeFSMount) GetMasters() []string {
	if x != nil {
		return x.Masters
	}
	return nil
}

func (x *CubeFSMount) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CubeFSMount) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *CubeFSMount) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CubeFSMount) GetSubdir() string {
	if x != nil {
		return x.Subdir
	}
	return ""
}

// WireGuard is the optional kernel WireGuard overlay weft-init brings up
// after eth0. Keys are base64-encoded 32-byte Curve25519 values. Mirrors
// weft-microvm-init/pkg/pod.WireGuard.
type WireGuard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`                      // default "wg0"
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`  // base64, 32 bytes
	ListenPort    uint32                 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"` // UDP underlay port; 0 = ephemeral
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                          // overlay CIDR, e.g. "10.9.0.1/24"
	Peers         []*WGPeer              `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuard) Reset() {
	*x = WireGuard{}
	mi := &file_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuard) ProtoMessage() {}

func (x *WireGuard) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuard.ProtoReflect.Descriptor instead.
func (*WireGuard) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{3}
}

func (x *WireGuard) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *WireGuard) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireGuard) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *WireGuard) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireGuard) GetPeers() []*WGPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WGPeer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                                // base64, 32 bytes
	Endpoint            string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                                   // underlay "host:port"
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`                             // overlay CIDRs routed to this peer
	PersistentKeepalive uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"` // seconds; 0 = disabled
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WGPeer) Reset() {
	*x = WGPeer{}
	mi := &file_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WGPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WGPeer) ProtoMessage() {}

func (x *WGPeer) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WGPeer.ProtoReflect.Descriptor instead.
func (*WGPeer) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{4}
}

func (x *WGPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WGPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WGPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WGPeer) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RootfsTag     string                 `protobuf:"bytes,2,opt,name=rootfs_tag,json=rootfsTag,proto3" json:"rootfs_tag,omitempty"` // matches a Share.tag (virtio-fs) OR a path under /run/weft/rootfs/<id>
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir       string                 `protobuf:"bytes,6,opt,name=workdir,proto3" json:"workdir,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"` // "uid:gid" or username
	Restart       RestartPolicy          `protobuf:"varint,8,opt,name=restart,proto3,enum=weft.guest.v1.RestartPolicy" json:"restart,omitempty"`
	Mounts        []*Mount               `protobuf:"bytes,9,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Resources     *Resources             `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	Privileged    bool                   `protobuf:"varint,11,opt,name=privileged,proto3" json:"privileged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{5}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetRootfsTag() string {
	if x != nil {
		return x.RootfsTag
	}
	return ""
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Container) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Container) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Container) GetRestart() RestartPolicy {
	if x != nil {
		return x.Restart
	}
	return RestartPolicy_RESTART_NEVER
}

func (x *Container) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Container) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Container) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

type Share struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{6}
}

func (x *Share) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Share) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *Share) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"` // default "eth0"
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`     // CIDR, e.g. "10.0.2.15/24"
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns           []string               `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{7}
}

func (x *Network) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Network) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Network) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Network) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *Network) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{8}
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuShares     uint64                 `protobuf:"varint,1,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	MemBytes      uint64                 `protobuf:"varint,2,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	PidsMax       int64                  `protobuf:"varint,3,opt,name=pids_max,json=pidsMax,proto3" json:"pids_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{9}
}

func (x *Resources) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *Resources) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *Resources) GetPidsMax() int64 {
	if x != nil {
		return x.PidsMax
	}
	return 0
}

type GuestFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*GuestFrame_Hello
	//	*GuestFrame_HelloAck
	//	*GuestFrame_PodStatus
	//	*GuestFrame_CtrEvent
	//	*GuestFrame_Log
	//	*GuestFrame_ControlReq
	//	*GuestFrame_ControlResp
	Body          isGuestFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestFrame) Reset() {
	*x = GuestFrame{}
	mi := &file_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestFrame) ProtoMessage() {}

func (x *GuestFrame) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestFrame.ProtoReflect.Descriptor instead.
func (*GuestFrame) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{10}
}

func (x *GuestFrame) GetBody() isGuestFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GuestFrame) GetHello() *GuestHello {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *GuestFrame) GetHelloAck() *GuestHelloAck {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *GuestFrame) GetPodStatus() *PodStatus {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_PodStatus); ok {
			return x.PodStatus
		}
	}
	return nil
}

func (x *GuestFrame) GetCtrEvent() *ContainerEvent {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_CtrEvent); ok {
			return x.CtrEvent
		}
	}
	return nil
}

func (x *GuestFrame) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *GuestFrame) GetControlReq() *ControlRequest {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_ControlReq); ok {
			return x.ControlReq
		}
	}
	return nil
}

func (x *GuestFrame) GetControlResp() *ControlResponse {
	if x != nil {
		if x, ok := x.Body.(*GuestFrame_ControlResp); ok {
			return x.ControlResp
		}
	}
	return nil
}

type isGuestFrame_Body interface {
	isGuestFrame_Body()
}

type GuestFrame_Hello struct {
	Hello *GuestHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // guest → host, always first
}

type GuestFrame_HelloAck struct {
	HelloAck *GuestHelloAck `protobuf:"bytes,2,opt,name=hello_ack,json=helloAck,proto3,oneof"` // host → guest
}

type GuestFrame_PodStatus struct {
	PodStatus *PodStatus `protobuf:"bytes,3,opt,name=pod_status,json=podStatus,proto3,oneof"` // guest → host, periodic
}

type GuestFrame_CtrEvent struct {
	CtrEvent *ContainerEvent `protobuf:"bytes,4,opt,name=ctr_event,json=ctrEvent,proto3,oneof"` // guest → host, on every state change
}

type GuestFrame_Log struct {
	Log *LogChunk `protobuf:"bytes,5,opt,name=log,proto3,oneof"` // guest → host, stream of stdio
}

type GuestFrame_ControlReq struct {
	ControlReq *ControlRequest `protobuf:"bytes,6,opt,name=control_req,json=controlReq,proto3,oneof"` // host → guest
}

type GuestFrame_ControlResp struct {
	ControlResp *ControlResponse `protobuf:"bytes,7,opt,name=control_resp,json=controlResp,proto3,oneof"` // guest → host
}

func (*GuestFrame_Hello) isGuestFrame_Body() {}

func (*GuestFrame_HelloAck) isGuestFrame_Body() {}

func (*GuestFrame_PodStatus) isGuestFrame_Body() {}

func (*GuestFrame_CtrEvent) isGuestFrame_Body() {}

func (*GuestFrame_Log) isGuestFrame_Body() {}

func (*GuestFrame_ControlReq) isGuestFrame_Body() {}

func (*GuestFrame_ControlResp) isGuestFrame_Body() {}

type GuestHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodId         string                 `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	InitVersion   string                 `protobuf:"bytes,2,opt,name=init_version,json=initVersion,proto3" json:"init_version,omitempty"` // build SHA / semver of weft-init
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`                              // uname -r
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`                  // "amd64" | "arm64"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestHello) Reset() {
	*x = GuestHello{}
	mi := &file_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestHello) ProtoMessage() {}

func (x *GuestHello) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestHello.ProtoReflect.Descriptor instead.
func (*GuestHello) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{11}
}

func (x *GuestHello) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *GuestHello) GetInitVersion() string {
	if x != nil {
		return x.InitVersion
	}
	return ""
}

func (x *GuestHello) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *GuestHello) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type GuestHelloAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The host's authoritative PodSpec ; the guest reconciles its
	// view against this. If the spec embedded at boot (cloud-init
	// ISO / virtio-fs / cmdline) is already current, this echoes
	// it back ; if the host has a newer revision, the guest
	// applies the delta.
	Spec          *PodSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestHelloAck) Reset() {
	*x = GuestHelloAck{}
	mi := &file_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestHelloAck) ProtoMessage() {}

func (x *GuestHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestHelloAck.ProtoReflect.Descriptor instead.
func (*GuestHelloAck) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{12}
}

func (x *GuestHelloAck) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PodStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodId         string                 `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Containers    []*ContainerStatus     `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	UptimeMs      uint64                 `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{13}
}

func (x *PodStatus) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *PodStatus) GetContainers() []*ContainerStatus {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodStatus) GetUptimeMs() uint64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "created" | "running" | "stopped"
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signaled      bool                   `protobuf:"varint,5,opt,name=signaled,proto3" json:"signaled,omitempty"`
	Signal        int32                  `protobuf:"varint,6,opt,name=signal,proto3" json:"signal,omitempty"`
	RestartCount  int32                  `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,8,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	ExitedAtMs    int64                  `protobuf:"varint,9,opt,name=exited_at_ms,json=exitedAtMs,proto3" json:"exited_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ContainerStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerStatus) GetSignaled() bool {
	if x != nil {
		return x.Signaled
	}
	return false
}

func (x *ContainerStatus) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *ContainerStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ContainerStatus) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *ContainerStatus) GetExitedAtMs() int64 {
	if x != nil {
		return x.ExitedAtMs
	}
	return 0
}

type ContainerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "created" | "started" | "exited" | "oom"
	Status        *ContainerStatus       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{15}
}

func (x *ContainerEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContainerEvent) GetStatus() *ContainerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Stream        Stream                 `protobuf:"varint,2,opt,name=stream,proto3,enum=weft.guest.v1.Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{16}
}

func (x *LogChunk) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogChunk) GetStream() Stream {
	if x != nil {
		return x.Stream
	}
	return Stream_STREAM_UNSPECIFIED
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// ControlRequest is host → guest. The guest answers with a
// matching ControlResponse carrying the same call_id.
type ControlRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId uint64                 `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*ControlRequest_StopPod
	//	*ControlRequest_Kill
	//	*ControlRequest_Exec
	//	*ControlRequest_Update
	Op            isControlRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_guest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{17}
}

func (x *ControlRequest) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *ControlRequest) GetOp() isControlRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ControlRequest) GetStopPod() *StopPod {
	if x != nil {
		if x, ok := x.Op.(*ControlRequest_StopPod); ok {
			return x.StopPod
		}
	}
	return nil
}

func (x *ControlRequest) GetKill() *KillContainer {
	if x != nil {
		if x, ok := x.Op.(*ControlRequest_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

func (x *ControlRequest) GetExec() *ExecInContainer {
	if x != nil {
		if x, ok := x.Op.(*ControlRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ControlRequest) GetUpdate() *UpdateContainer {
	if x != nil {
		if x, ok := x.Op.(*ControlRequest_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isControlRequest_Op interface {
	isControlRequest_Op()
}

type ControlRequest_StopPod struct {
	StopPod *StopPod `protobuf:"bytes,10,opt,name=stop_pod,json=stopPod,proto3,oneof"`
}

type ControlRequest_Kill struct {
	Kill *KillContainer `protobuf:"bytes,11,opt,name=kill,proto3,oneof"`
}

type ControlRequest_Exec struct {
	Exec *ExecInContainer `protobuf:"bytes,12,opt,name=exec,proto3,oneof"`
}

type ControlRequest_Update struct {
	Update *UpdateContainer `protobuf:"bytes,13,opt,name=update,proto3,oneof"` // future: live restart with new env / cmd
}

func (*ControlRequest_StopPod) isControlRequest_Op() {}

func (*ControlRequest_Kill) isControlRequest_Op() {}

func (*ControlRequest_Exec) isControlRequest_Op() {}

func (*ControlRequest_Update) isControlRequest_Op() {}

type ControlResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId uint64                 `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Error  string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlResponse_ExecResult
	Payload       isControlResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_guest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{18}
}

func (x *ControlResponse) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *ControlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ControlResponse) GetPayload() isControlResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlResponse) GetExecResult() *ExecResult {
	if x != nil {
		if x, ok := x.Payload.(*ControlResponse_ExecResult); ok {
			return x.ExecResult
		}
	}
	return nil
}

type isControlResponse_Payload interface {
	isControlResponse_Payload()
}

type ControlResponse_ExecResult struct {
	ExecResult *ExecResult `protobuf:"bytes,10,opt,name=exec_result,json=execResult,proto3,oneof"`
}

func (*ControlResponse_ExecResult) isControlResponse_Payload() {}

type StopPod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceSeconds  uint32                 `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPod) Reset() {
	*x = StopPod{}
	mi := &file_guest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPod) ProtoMessage() {}

func (x *StopPod) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPod.ProtoReflect.Descriptor instead.
func (*StopPod) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{19}
}

func (x *StopPod) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type KillContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"` // "TERM" | "KILL" | …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillContainer) Reset() {
	*x = KillContainer{}
	mi := &file_guest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillContainer) ProtoMessage() {}

func (x *KillContainer) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillContainer.ProtoReflect.Descriptor instead.
func (*KillContainer) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{20}
}

func (x *KillContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *KillContainer) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type ExecInContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInContainer) Reset() {
	*x = ExecInContainer{}
	mi := &file_guest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInContainer) ProtoMessage() {}

func (x *ExecInContainer) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInContainer.ProtoReflect.Descriptor instead.
func (*ExecInContainer) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{21}
}

func (x *ExecInContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecInContainer) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecInContainer) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecInContainer) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type ExecResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signaled      bool                   `protobuf:"varint,2,opt,name=signaled,proto3" json:"signaled,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"` // small payloads only ; streaming exec uses a future side-channel
	Stderr        []byte                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_guest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{22}
}

func (x *ExecResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResult) GetSignaled() bool {
	if x != nil {
		return x.Signaled
	}
	return false
}

func (x *ExecResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

// UpdateContainer is the future live-restart op : swap a container's
// env / command without a full pod restart. The body is intentionally
// minimal today ; flesh out when the runtime grows the matching API
// (weft-init has no live-update path yet).
type UpdateContainer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// command, if non-empty, replaces the container's command line.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// env merges over the container's existing env ; empty value
	// unsets a key.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContainer) Reset() {
	*x = UpdateContainer{}
	mi := &file_guest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContainer) ProtoMessage() {}

func (x *UpdateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContainer.ProtoReflect.Descriptor instead.
func (*UpdateContainer) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *UpdateContainer) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *UpdateContainer) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

var File_guest_proto protoreflect.FileDescriptor

const file_guest_proto_rawDesc = "" +
	"\n" +
	"\vguest.proto\x12\rweft.guest.v1\"\xb7\x03\n" +
	"\aPodSpec\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podId\x128\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x18.weft.guest.v1.ContainerR\n" +
	"containers\x12,\n" +
	"\x06shares\x18\x03 \x03(\v2\x14.weft.guest.v1.ShareR\x06shares\x120\n" +
	"\anetwork\x18\x04 \x01(\v2\x16.weft.guest.v1.NetworkR\anetwork\x12F\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2&.weft.guest.v1.PodSpec.PropertiesEntryR\n" +
	"properties\x126\n" +
	"\twireguard\x18\x06 \x01(\v2\x18.weft.guest.v1.WireGuardR\twireguard\x12<\n" +
	"\fshare_mounts\x18\a \x03(\v2\x19.weft.guest.v1.ShareMountR\vshareMounts\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\n" +
	"ShareMount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x1f\n" +
	"\vmount_point\x18\x04 \x01(\tR\n" +
	"mountPoint\x12\x1a\n" +
	"\breadonly\x18\x05 \x01(\bR\breadonly\x122\n" +
	"\x06cubefs\x18\x06 \x01(\v2\x1a.weft.guest.v1.CubeFSMountR\x06cubefs\"\xab\x01\n" +
	"\vCubeFSMount\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x18\n" +
	"\amasters\x18\x02 \x03(\tR\amasters\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06subdir\x18\x06 \x01(\tR\x06subdir\"\xb2\x01\n" +
	"\tWireGuard\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12+\n" +
	"\x05peers\x18\x05 \x03(\v2\x15.weft.guest.v1.WGPeerR\x05peers\"\x97\x01\n" +
	"\x06WGPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x04 \x01(\rR\x13persistentKeepalive\"\xc1\x03\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"rootfs_tag\x18\x02 \x01(\tR\trootfsTag\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x123\n" +
	"\x03env\x18\x05 \x03(\v2!.weft.guest.v1.Container.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\x06 \x01(\tR\aworkdir\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x126\n" +
	"\arestart\x18\b \x01(\x0e2\x1c.weft.guest.v1.RestartPolicyR\arestart\x12,\n" +
	"\x06mounts\x18\t \x03(\v2\x14.weft.guest.v1.MountR\x06mounts\x126\n" +
	"\tresources\x18\n" +
	" \x01(\v2\x18.weft.guest.v1.ResourcesR\tresources\x12\x1e\n" +
	"\n" +
	"privileged\x18\v \x01(\bR\n" +
	"privileged\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x05Share\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"\x89\x01\n" +
	"\aNetwork\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\x04 \x03(\tR\x03dns\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\"o\n" +
	"\x05Mount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"b\n" +
	"\tResources\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x01 \x01(\x04R\tcpuShares\x12\x1b\n" +
	"\tmem_bytes\x18\x02 \x01(\x04R\bmemBytes\x12\x19\n" +
	"\bpids_max\x18\x03 \x01(\x03R\apidsMax\"\xb1\x03\n" +
	"\n" +
	"GuestFrame\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.weft.guest.v1.GuestHelloH\x00R\x05hello\x12;\n" +
	"\thello_ack\x18\x02 \x01(\v2\x1c.weft.guest.v1.GuestHelloAckH\x00R\bhelloAck\x129\n" +
	"\n" +
	"pod_status\x18\x03 \x01(\v2\x18.weft.guest.v1.PodStatusH\x00R\tpodStatus\x12<\n" +
	"\tctr_event\x18\x04 \x01(\v2\x1d.weft.guest.v1.ContainerEventH\x00R\bctrEvent\x12+\n" +
	"\x03log\x18\x05 \x01(\v2\x17.weft.guest.v1.LogChunkH\x00R\x03log\x12@\n" +
	"\vcontrol_req\x18\x06 \x01(\v2\x1d.weft.guest.v1.ControlRequestH\x00R\n" +
	"controlReq\x12C\n" +
	"\fcontrol_resp\x18\a \x01(\v2\x1e.weft.guest.v1.ControlResponseH\x00R\vcontrolRespB\x06\n" +
	"\x04body\"\x82\x01\n" +
	"\n" +
	"GuestHello\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podId\x12!\n" +
	"\finit_version\x18\x02 \x01(\tR\vinitVersion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\";\n" +
	"\rGuestHelloAck\x12*\n" +
	"\x04spec\x18\x01 \x01(\v2\x16.weft.guest.v1.PodSpecR\x04spec\"\x7f\n" +
	"\tPodStatus\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podId\x12>\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x1e.weft.guest.v1.ContainerStatusR\n" +
	"containers\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x04R\buptimeMs\"\x85\x02\n" +
	"\x0fContainerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1a\n" +
	"\bsignaled\x18\x05 \x01(\bR\bsignaled\x12\x16\n" +
	"\x06signal\x18\x06 \x01(\x05R\x06signal\x12#\n" +
	"\rrestart_count\x18\a \x01(\x05R\frestartCount\x12\"\n" +
	"\rstarted_at_ms\x18\b \x01(\x03R\vstartedAtMs\x12 \n" +
	"\fexited_at_ms\x18\t \x01(\x03R\n" +
	"exitedAtMs\"l\n" +
	"\x0eContainerEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x126\n" +
	"\x06status\x18\x03 \x01(\v2\x1e.weft.guest.v1.ContainerStatusR\x06status\"\x93\x01\n" +
	"\bLogChunk\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12-\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x15.weft.guest.v1.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"\x88\x02\n" +
	"\x0eControlRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x04R\x06callId\x123\n" +
	"\bstop_pod\x18\n" +
	" \x01(\v2\x16.weft.guest.v1.StopPodH\x00R\astopPod\x122\n" +
	"\x04kill\x18\v \x01(\v2\x1c.weft.guest.v1.KillContainerH\x00R\x04kill\x124\n" +
	"\x04exec\x18\f \x01(\v2\x1e.weft.guest.v1.ExecInContainerH\x00R\x04exec\x128\n" +
	"\x06update\x18\r \x01(\v2\x1e.weft.guest.v1.UpdateContainerH\x00R\x06updateB\x04\n" +
	"\x02op\"\x89\x01\n" +
	"\x0fControlResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x04R\x06callId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12<\n" +
	"\vexec_result\x18\n" +
	" \x01(\v2\x19.weft.guest.v1.ExecResultH\x00R\n" +
	"execResultB\t\n" +
	"\apayload\".\n" +
	"\aStopPod\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\rR\fgraceSeconds\"J\n" +
	"\rKillContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\xd3\x01\n" +
	"\x0fExecInContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x129\n" +
	"\x03env\x18\x03 \x03(\v2'.weft.guest.v1.ExecInContainer.EnvEntryR\x03env\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\n" +
	"ExecResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1a\n" +
	"\bsignaled\x18\x02 \x01(\bR\bsignaled\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderr\"\xc1\x01\n" +
	"\x0fUpdateContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x129\n" +
	"\x03env\x18\x03 \x03(\v2'.weft.guest.v1.UpdateContainer.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*N\n" +
	"\rRestartPolicy\x12\x11\n" +
	"\rRESTART_NEVER\x10\x00\x12\x16\n" +
	"\x12RESTART_ON_FAILURE\x10\x01\x12\x12\n" +
	"\x0eRESTART_ALWAYS\x10\x02*F\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTREAM_STDOUT\x10\x01\x12\x11\n" +
	"\rSTREAM_STDERR\x10\x022S\n" +
	"\rGuestPodPlane\x12B\n" +
	"\x06Attach\x12\x19.weft.guest.v1.GuestFrame\x1a\x19.weft.guest.v1.GuestFrame(\x010\x01B0Z.github.com/openweft/weft-proto/guestv1;guestv1b\x06proto3"

var (
	file_guest_proto_rawDescOnce sync.Once
	file_guest_proto_rawDescData []byte
)

func file_guest_proto_rawDescGZIP() []byte {
	file_guest_proto_rawDescOnce.Do(func() {
		file_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_proto_rawDesc), len(file_guest_proto_rawDesc)))
	})
	return file_guest_proto_rawDescData
}

var file_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_guest_proto_goTypes = []any{
	(RestartPolicy)(0),      // 0: weft.guest.v1.RestartPolicy
	(Stream)(0),             // 1: weft.guest.v1.Stream
	(*PodSpec)(nil),         // 2: weft.guest.v1.PodSpec
	(*ShareMount)(nil),      // 3: weft.guest.v1.ShareMount
	(*CubeFSMount)(nil),     // 4: weft.guest.v1.CubeFSMount
	(*WireGuard)(nil),       // 5: weft.guest.v1.WireGuard
	(*WGPeer)(nil),          // 6: weft.guest.v1.WGPeer
	(*Container)(nil),       // 7: weft.guest.v1.Container
	(*Share)(nil),           // 8: weft.guest.v1.Share
	(*Network)(nil),         // 9: weft.guest.v1.Network
	(*Mount)(nil),           // 10: weft.guest.v1.Mount
	(*Resources)(nil),       // 11: weft.guest.v1.Resources
	(*GuestFrame)(nil),      // 12: weft.guest.v1.GuestFrame
	(*GuestHello)(nil),      // 13: weft.guest.v1.GuestHello
	(*GuestHelloAck)(nil),   // 14: weft.guest.v1.GuestHelloAck
	(*PodStatus)(nil),       // 15: weft.guest.v1.PodStatus
	(*ContainerStatus)(nil), // 16: weft.guest.v1.ContainerStatus
	(*ContainerEvent)(nil),  // 17: weft.guest.v1.ContainerEvent
	(*LogChunk)(nil),        // 18: weft.guest.v1.LogChunk
	(*ControlRequest)(nil),  // 19: weft.guest.v1.ControlRequest
	(*ControlResponse)(nil), // 20: weft.guest.v1.ControlResponse
	(*StopPod)(nil),         // 21: weft.guest.v1.StopPod
	(*KillContainer)(nil),   // 22: weft.guest.v1.KillContainer
	(*ExecInContainer)(nil), // 23: weft.guest.v1.ExecInContainer
	(*ExecResult)(nil),      // 24: weft.guest.v1.ExecResult
	(*UpdateContainer)(nil), // 25: weft.guest.v1.UpdateContainer
	nil,                     // 26: weft.guest.v1.PodSpec.PropertiesEntry
	nil,                     // 27: weft.guest.v1.Container.EnvEntry
	nil,                     // 28: weft.guest.v1.ExecInContainer.EnvEntry
	nil,                     // 29: weft.guest.v1.UpdateContainer.EnvEntry
}
var file_guest_proto_depIdxs = []int32{
	7,  // 0: weft.guest.v1.PodSpec.containers:type_name -> weft.guest.v1.Container
	8,  // 1: weft.guest.v1.PodSpec.shares:type_name -> weft.guest.v1.Share
	9,  // 2: weft.guest.v1.PodSpec.network:type_name -> weft.guest.v1.Network
	26, // 3: weft.guest.v1.PodSpec.properties:type_name -> weft.guest.v1.PodSpec.PropertiesEntry
	5,  // 4: weft.guest.v1.PodSpec.wireguard:type_name -> weft.guest.v1.WireGuard
	3,  // 5: weft.guest.v1.PodSpec.share_mounts:type_name -> weft.guest.v1.ShareMount
	4,  // 6: weft.guest.v1.ShareMount.cubefs:type_name -> weft.guest.v1.CubeFSMount
	6,  // 7: weft.guest.v1.WireGuard.peers:type_name -> weft.guest.v1.WGPeer
	27, // 8: weft.guest.v1.Container.env:type_name -> weft.guest.v1.Container.EnvEntry
	0,  // 9: weft.guest.v1.Container.restart:type_name -> weft.guest.v1.RestartPolicy
	10, // 10: weft.guest.v1.Container.mounts:type_name -> weft.guest.v1.Mount
	11, // 11: weft.guest.v1.Container.resources:type_name -> weft.guest.v1.Resources
	13, // 12: weft.guest.v1.GuestFrame.hello:type_name -> weft.guest.v1.GuestHello
	14, // 13: weft.guest.v1.GuestFrame.hello_ack:type_name -> weft.guest.v1.GuestHelloAck
	15, // 14: weft.guest.v1.GuestFrame.pod_status:type_name -> weft.guest.v1.PodStatus
	17, // 15: weft.guest.v1.GuestFrame.ctr_event:type_name -> weft.guest.v1.ContainerEvent
	18, // 16: weft.guest.v1.GuestFrame.log:type_name -> weft.guest.v1.LogChunk
	19, // 17: weft.guest.v1.GuestFrame.control_req:type_name -> weft.guest.v1.ControlRequest
	20, // 18: weft.guest.v1.GuestFrame.control_resp:type_name -> weft.guest.v1.ControlResponse
	2,  // 19: weft.guest.v1.GuestHelloAck.spec:type_name -> weft.guest.v1.PodSpec
	16, // 20: weft.guest.v1.PodStatus.containers:type_name -> weft.guest.v1.ContainerStatus
	16, // 21: weft.guest.v1.ContainerEvent.status:type_name -> weft.guest.v1.ContainerStatus
	1,  // 22: weft.guest.v1.LogChunk.stream:type_name -> weft.guest.v1.Stream
	21, // 23: weft.guest.v1.ControlRequest.stop_pod:type_name -> weft.guest.v1.StopPod
	22, // 24: weft.guest.v1.ControlRequest.kill:type_name -> weft.guest.v1.KillContainer
	23, // 25: weft.guest.v1.ControlRequest.exec:type_name -> weft.guest.v1.ExecInContainer
	25, // 26: weft.guest.v1.ControlRequest.update:type_name -> weft.guest.v1.UpdateContainer
	24, // 27: weft.guest.v1.ControlResponse.exec_result:type_name -> weft.guest.v1.ExecResult
	28, // 28: weft.guest.v1.ExecInContainer.env:type_name -> weft.guest.v1.ExecInContainer.EnvEntry
	29, // 29: weft.guest.v1.UpdateContainer.env:type_name -> weft.guest.v1.UpdateContainer.EnvEntry
	12, // 30: weft.guest.v1.GuestPodPlane.Attach:input_type -> weft.guest.v1.GuestFrame
	12, // 31: weft.guest.v1.GuestPodPlane.Attach:output_type -> weft.guest.v1.GuestFrame
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_guest_proto_init() }
func file_guest_proto_init() {
	if File_guest_proto != nil {
		return
	}
	file_guest_proto_msgTypes[10].OneofWrappers = []any{
		(*GuestFrame_Hello)(nil),
		(*GuestFrame_HelloAck)(nil),
		(*GuestFrame_PodStatus)(nil),
		(*GuestFrame_CtrEvent)(nil),
		(*GuestFrame_Log)(nil),
		(*GuestFrame_ControlReq)(nil),
		(*GuestFrame_ControlResp)(nil),
	}
	file_guest_proto_msgTypes[17].OneofWrappers = []any{
		(*ControlRequest_StopPod)(nil),
		(*ControlRequest_Kill)(nil),
		(*ControlRequest_Exec)(nil),
		(*ControlRequest_Update)(nil),
	}
	file_guest_proto_msgTypes[18].OneofWrappers = []any{
		(*ControlResponse_ExecResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_proto_rawDesc), len(file_guest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guest_proto_goTypes,
		DependencyIndexes: file_guest_proto_depIdxs,
		EnumInfos:         file_guest_proto_enumTypes,
		MessageInfos:      file_guest_proto_msgTypes,
	}.Build()
	File_guest_proto = out.File
	file_guest_proto_goTypes = nil
	file_guest_proto_depIdxs = nil
}
