// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: guest.proto

// guest.proto defines the guest-side transport between weft-init
// (PID 1 inside an openweft micro-VM) and weft-agent (running on
// the hypervisor host).
//
// Two services live here:
//
//   * `GuestPodPlane` — what the guest dials on the host side.
//     The host listens on AF_VSOCK ; the guest opens a long-lived
//     bidirectional stream and reports pod / container events,
//     log chunks, and replies to control requests the host injects.
//
//   * `PodLifecycle` (future, not yet wired) — what the operator-
//     facing weft-agent surfaces upward to the control plane to
//     drive pod creation / mutation. Kept here so the type system
//     for PodSpec stays single-sourced.
//
// Mirrors agent.proto's split: machine-to-machine RPCs live in
// their own file with their own auth boundary (vsock identity is
// implicit — the guest's CID identifies the VM, the host enforces
// per-VM access policy in weft-agent before responding).
//
// See [[openweft-module-layout]] for placement.

package guestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestPodPlane_Attach_FullMethodName = "/weft.guest.v1.GuestPodPlane/Attach"
)

// GuestPodPlaneClient is the client API for GuestPodPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuestPodPlaneClient interface {
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GuestFrame, GuestFrame], error)
}

type guestPodPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestPodPlaneClient(cc grpc.ClientConnInterface) GuestPodPlaneClient {
	return &guestPodPlaneClient{cc}
}

func (c *guestPodPlaneClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GuestFrame, GuestFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestPodPlane_ServiceDesc.Streams[0], GuestPodPlane_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GuestFrame, GuestFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestPodPlane_AttachClient = grpc.BidiStreamingClient[GuestFrame, GuestFrame]

// GuestPodPlaneServer is the server API for GuestPodPlane service.
// All implementations must embed UnimplementedGuestPodPlaneServer
// for forward compatibility.
type GuestPodPlaneServer interface {
	Attach(grpc.BidiStreamingServer[GuestFrame, GuestFrame]) error
	mustEmbedUnimplementedGuestPodPlaneServer()
}

// UnimplementedGuestPodPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestPodPlaneServer struct{}

func (UnimplementedGuestPodPlaneServer) Attach(grpc.BidiStreamingServer[GuestFrame, GuestFrame]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedGuestPodPlaneServer) mustEmbedUnimplementedGuestPodPlaneServer() {}
func (UnimplementedGuestPodPlaneServer) testEmbeddedByValue()                       {}

// UnsafeGuestPodPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestPodPlaneServer will
// result in compilation errors.
type UnsafeGuestPodPlaneServer interface {
	mustEmbedUnimplementedGuestPodPlaneServer()
}

func RegisterGuestPodPlaneServer(s grpc.ServiceRegistrar, srv GuestPodPlaneServer) {
	// If the following call panics, it indicates UnimplementedGuestPodPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestPodPlane_ServiceDesc, srv)
}

func _GuestPodPlane_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuestPodPlaneServer).Attach(&grpc.GenericServerStream[GuestFrame, GuestFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestPodPlane_AttachServer = grpc.BidiStreamingServer[GuestFrame, GuestFrame]

// GuestPodPlane_ServiceDesc is the grpc.ServiceDesc for GuestPodPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestPodPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.guest.v1.GuestPodPlane",
	HandlerType: (*GuestPodPlaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _GuestPodPlane_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "guest.proto",
}
