// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: introspect.proto

// introspect.proto defines the read-only introspection service a
// micro-VM exposes directly to an operator's CLI over the WireGuard
// overlay (wg0). Unlike guest.proto's GuestPodPlane — which the guest
// dials OUT to weft-agent over vsock — Introspect is a server the guest
// LISTENS on, bound to its wg0 address. The CLI reaches it end-to-end
// encrypted via github.com/openweft/weft-client/wgdial, so the traffic
// is confidential even from the hypervisor host.
//
// Kept in its own file/package (introspectv1) so it generates and
// versions independently of the vsock plane.

package introspectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Introspect_ListProcesses_FullMethodName = "/weft.introspect.v1.Introspect/ListProcesses"
)

// IntrospectClient is the client API for Introspect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Introspect is the VM-side read-only inspection API.
type IntrospectClient interface {
	// ListProcesses returns the VM's process table — the gRPC equivalent
	// of `ps aux`, sourced from the guest's /proc.
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
}

type introspectClient struct {
	cc grpc.ClientConnInterface
}

func NewIntrospectClient(cc grpc.ClientConnInterface) IntrospectClient {
	return &introspectClient{cc}
}

func (c *introspectClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, Introspect_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntrospectServer is the server API for Introspect service.
// All implementations must embed UnimplementedIntrospectServer
// for forward compatibility.
//
// Introspect is the VM-side read-only inspection API.
type IntrospectServer interface {
	// ListProcesses returns the VM's process table — the gRPC equivalent
	// of `ps aux`, sourced from the guest's /proc.
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	mustEmbedUnimplementedIntrospectServer()
}

// UnimplementedIntrospectServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntrospectServer struct{}

func (UnimplementedIntrospectServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedIntrospectServer) mustEmbedUnimplementedIntrospectServer() {}
func (UnimplementedIntrospectServer) testEmbeddedByValue()                    {}

// UnsafeIntrospectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntrospectServer will
// result in compilation errors.
type UnsafeIntrospectServer interface {
	mustEmbedUnimplementedIntrospectServer()
}

func RegisterIntrospectServer(s grpc.ServiceRegistrar, srv IntrospectServer) {
	// If the following call panics, it indicates UnimplementedIntrospectServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Introspect_ServiceDesc, srv)
}

func _Introspect_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntrospectServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Introspect_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntrospectServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Introspect_ServiceDesc is the grpc.ServiceDesc for Introspect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Introspect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.introspect.v1.Introspect",
	HandlerType: (*IntrospectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProcesses",
			Handler:    _Introspect_ListProcesses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "introspect.proto",
}
