// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: introspect.proto

// introspect.proto defines the read-only introspection service a
// micro-VM exposes directly to an operator's CLI over the WireGuard
// overlay (wg0). Unlike guest.proto's GuestPodPlane — which the guest
// dials OUT to weft-agent over vsock — Introspect is a server the guest
// LISTENS on, bound to its wg0 address. The CLI reaches it end-to-end
// encrypted via github.com/openweft/weft-client/wgdial, so the traffic
// is confidential even from the hypervisor host.
//
// Kept in its own file/package (introspectv1) so it generates and
// versions independently of the vsock plane.

package introspectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_introspect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_introspect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_introspect_proto_rawDescGZIP(), []int{0}
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_introspect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_introspect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_introspect_proto_rawDescGZIP(), []int{1}
}

func (x *ListProcessesResponse) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Process mirrors one row of `ps aux`.
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                                      // resolved from /proc/<pid>/status Uid; falls back to the numeric uid
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                    // single-letter Linux process state (R, S, D, Z, T, …)
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`      // lifetime-average %CPU, same definition ps uses
	MemPercent    float64                `protobuf:"fixed64,6,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`      // RSS / MemTotal * 100
	VszKb         uint64                 `protobuf:"varint,7,opt,name=vsz_kb,json=vszKb,proto3" json:"vsz_kb,omitempty"`                      // virtual size (VmSize)
	RssKb         uint64                 `protobuf:"varint,8,opt,name=rss_kb,json=rssKb,proto3" json:"rss_kb,omitempty"`                      // resident set size (VmRSS)
	Tty           string                 `protobuf:"bytes,9,opt,name=tty,proto3" json:"tty,omitempty"`                                        // controlling terminal, "?" when none
	StartTimeMs   int64                  `protobuf:"varint,10,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"` // process start, unix epoch milliseconds
	Command       string                 `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`                               // full cmdline (NUL-joined argv), or [comm] for kernel threads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_introspect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_introspect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_introspect_proto_rawDescGZIP(), []int{2}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Process) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Process) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Process) GetVszKb() uint64 {
	if x != nil {
		return x.VszKb
	}
	return 0
}

func (x *Process) GetRssKb() uint64 {
	if x != nil {
		return x.RssKb
	}
	return 0
}

func (x *Process) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *Process) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *Process) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

var File_introspect_proto protoreflect.FileDescriptor

const file_introspect_proto_rawDesc = "" +
	"\n" +
	"\x10introspect.proto\x12\x12weft.introspect.v1\"\x16\n" +
	"\x14ListProcessesRequest\"R\n" +
	"\x15ListProcessesResponse\x129\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1b.weft.introspect.v1.ProcessR\tprocesses\"\x99\x02\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x06 \x01(\x01R\n" +
	"memPercent\x12\x15\n" +
	"\x06vsz_kb\x18\a \x01(\x04R\x05vszKb\x12\x15\n" +
	"\x06rss_kb\x18\b \x01(\x04R\x05rssKb\x12\x10\n" +
	"\x03tty\x18\t \x01(\tR\x03tty\x12\"\n" +
	"\rstart_time_ms\x18\n" +
	" \x01(\x03R\vstartTimeMs\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand2r\n" +
	"\n" +
	"Introspect\x12d\n" +
	"\rListProcesses\x12(.weft.introspect.v1.ListProcessesRequest\x1a).weft.introspect.v1.ListProcessesResponseB:Z8github.com/openweft/weft-proto/introspectv1;introspectv1b\x06proto3"

var (
	file_introspect_proto_rawDescOnce sync.Once
	file_introspect_proto_rawDescData []byte
)

func file_introspect_proto_rawDescGZIP() []byte {
	file_introspect_proto_rawDescOnce.Do(func() {
		file_introspect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_introspect_proto_rawDesc), len(file_introspect_proto_rawDesc)))
	})
	return file_introspect_proto_rawDescData
}

var file_introspect_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_introspect_proto_goTypes = []any{
	(*ListProcessesRequest)(nil),  // 0: weft.introspect.v1.ListProcessesRequest
	(*ListProcessesResponse)(nil), // 1: weft.introspect.v1.ListProcessesResponse
	(*Process)(nil),               // 2: weft.introspect.v1.Process
}
var file_introspect_proto_depIdxs = []int32{
	2, // 0: weft.introspect.v1.ListProcessesResponse.processes:type_name -> weft.introspect.v1.Process
	0, // 1: weft.introspect.v1.Introspect.ListProcesses:input_type -> weft.introspect.v1.ListProcessesRequest
	1, // 2: weft.introspect.v1.Introspect.ListProcesses:output_type -> weft.introspect.v1.ListProcessesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_introspect_proto_init() }
func file_introspect_proto_init() {
	if File_introspect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_introspect_proto_rawDesc), len(file_introspect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_introspect_proto_goTypes,
		DependencyIndexes: file_introspect_proto_depIdxs,
		MessageInfos:      file_introspect_proto_msgTypes,
	}.Build()
	File_introspect_proto = out.File
	file_introspect_proto_goTypes = nil
	file_introspect_proto_depIdxs = nil
}
