// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: agent.proto

// agent.proto defines the control-plane ↔ agent transport. One
// `AgentControlPlane` service that the agent dials at startup ;
// one `AttachDrivers` bidirectional stream the control plane
// uses to dispatch driver calls (Hypervisor / Network / Volume
// / Image) back into the agent.
//
// Why a separate file from weft.proto:
//
//   * `WeftService` is the public operator API (CLI, dashboard,
//     terraform-provider). It carries operator-side
//     RegisterHost/Heartbeat too — but those are operator
//     intent, surfaced under operator auth.
//   * `AgentControlPlane` is internal traffic, machine-to-
//     machine, with agent-identity auth (mTLS client cert, in
//     the simplest setup). Keeping it in its own .proto file +
//     its own service name makes the security policy easy to
//     state ("operators don't speak AgentControlPlane ; only
//     weft-agents do").
//
// See [[openweft-module-layout]] for the broader naming map and
// [[weft-driver-registry-split]] for why each driver type
// surfaces here individually.

package agentv1

import (
	weft_proto "github.com/openweft/weft-proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HostRegistration is the agent's identity statement: who it
// is, what host it runs on, what capabilities the host has.
// Mirrors weft/agent.HostRegistration.
type HostRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID is the agent's persisted host-uuid. Empty means
	// "mint a new one" ; set means "I am this host, refresh my
	// entry idempotently".
	Uuid           string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hostname       string            `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Az             string            `protobuf:"bytes,3,opt,name=az,proto3" json:"az,omitempty"`
	Rack           string            `protobuf:"bytes,4,opt,name=rack,proto3" json:"rack,omitempty"`
	Endpoint       string            `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // host:port the control plane can dial back if needed
	Hypervisor     string            `protobuf:"bytes,6,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	Architecture   string            `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`
	NetworkTypes   []string          `protobuf:"bytes,8,rep,name=network_types,json=networkTypes,proto3" json:"network_types,omitempty"`
	VolumeBackends []string          `protobuf:"bytes,9,rep,name=volume_backends,json=volumeBackends,proto3" json:"volume_backends,omitempty"`
	Properties     map[string]string `protobuf:"bytes,10,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// agent_version is the weft binary's compile-time build version
	// (e.g. "v0.4.55"), stamped via -X main.version at link time.
	// Empty for unstamped dev builds. The control plane stores this
	// on the host registry so weft-tui / webui can show per-host
	// agent versions.
	AgentVersion string `protobuf:"bytes,11,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// driver_versions maps each loaded driver's kind ("vz" / "qemu"
	// / "block" / …) to its compile-time build version, harvested
	// by the agent at startup from each plugin's HostInfo() RPC.
	// Empty for legacy / unstamped builds. Persisted on the host
	// registry alongside the agent_version.
	DriverVersions map[string]string `protobuf:"bytes,12,rep,name=driver_versions,json=driverVersions,proto3" json:"driver_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// OS / kernel / hardware facts collected at register time.
	// See weft.proto HostInfo for field semantics ; the agent
	// populates these via /etc/os-release + /proc/sys/kernel/osrelease
	// + /sys/class/net + statfs(/proc/mounts). Linux-only ; other
	// platforms ship zero values.
	OsId              string                         `protobuf:"bytes,13,opt,name=os_id,json=osId,proto3" json:"os_id,omitempty"`
	OsVersion         string                         `protobuf:"bytes,14,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsPretty          string                         `protobuf:"bytes,15,opt,name=os_pretty,json=osPretty,proto3" json:"os_pretty,omitempty"`
	KernelVersion     string                         `protobuf:"bytes,16,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	NetworkInterfaces []*weft_proto.NetworkInterface `protobuf:"bytes,17,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	StorageMounts     []*weft_proto.StorageMount     `protobuf:"bytes,18,rep,name=storage_mounts,json=storageMounts,proto3" json:"storage_mounts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostRegistration) Reset() {
	*x = HostRegistration{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRegistration) ProtoMessage() {}

func (x *HostRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRegistration.ProtoReflect.Descriptor instead.
func (*HostRegistration) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HostRegistration) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HostRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostRegistration) GetAz() string {
	if x != nil {
		return x.Az
	}
	return ""
}

func (x *HostRegistration) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *HostRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HostRegistration) GetHypervisor() string {
	if x != nil {
		return x.Hypervisor
	}
	return ""
}

func (x *HostRegistration) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *HostRegistration) GetNetworkTypes() []string {
	if x != nil {
		return x.NetworkTypes
	}
	return nil
}

func (x *HostRegistration) GetVolumeBackends() []string {
	if x != nil {
		return x.VolumeBackends
	}
	return nil
}

func (x *HostRegistration) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *HostRegistration) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HostRegistration) GetDriverVersions() map[string]string {
	if x != nil {
		return x.DriverVersions
	}
	return nil
}

func (x *HostRegistration) GetOsId() string {
	if x != nil {
		return x.OsId
	}
	return ""
}

func (x *HostRegistration) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HostRegistration) GetOsPretty() string {
	if x != nil {
		return x.OsPretty
	}
	return ""
}

func (x *HostRegistration) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HostRegistration) GetNetworkInterfaces() []*weft_proto.NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *HostRegistration) GetStorageMounts() []*weft_proto.StorageMount {
	if x != nil {
		return x.StorageMounts
	}
	return nil
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *HostRegistration      `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentRequest) GetRegistration() *HostRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegisterAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assigned_uuid is the UUID the control plane registered the
	// host under. Matches request.registration.uuid in the
	// idempotent re-register case ; differs only when the request
	// came in with an empty uuid (the CP minted a fresh one).
	AssignedUuid  string `protobuf:"bytes,1,opt,name=assigned_uuid,json=assignedUuid,proto3" json:"assigned_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentResponse) GetAssignedUuid() string {
	if x != nil {
		return x.AssignedUuid
	}
	return ""
}

// HeartbeatRequest is what the agent sends on its heartbeat
// timer. The control plane bumps last_seen and flips the host's
// state Down → Active if applicable.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostUuid      string                 `protobuf:"bytes,1,opt,name=host_uuid,json=hostUuid,proto3" json:"host_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetHostUuid() string {
	if x != nil {
		return x.HostUuid
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type AttachDriversInit struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	HostUuid string                 `protobuf:"bytes,1,opt,name=host_uuid,json=hostUuid,proto3" json:"host_uuid,omitempty"`
	// Capability advertisement: which driver kinds this agent
	// can serve calls for. Control plane uses this to populate
	// the dispatch table's per-host driver tuple.
	DriverKinds   []string `protobuf:"bytes,2,rep,name=driver_kinds,json=driverKinds,proto3" json:"driver_kinds,omitempty"` // {"hypervisor", "network", "volume", "image"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDriversInit) Reset() {
	*x = AttachDriversInit{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDriversInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDriversInit) ProtoMessage() {}

func (x *AttachDriversInit) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDriversInit.ProtoReflect.Descriptor instead.
func (*AttachDriversInit) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AttachDriversInit) GetHostUuid() string {
	if x != nil {
		return x.HostUuid
	}
	return ""
}

func (x *AttachDriversInit) GetDriverKinds() []string {
	if x != nil {
		return x.DriverKinds
	}
	return nil
}

// AttachDriversFrame is the multiplexed envelope. The first
// frame on the stream is always init ; after that, dispatch +
// result alternate.
type AttachDriversFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AttachDriversFrame_Init
	//	*AttachDriversFrame_Dispatch
	//	*AttachDriversFrame_Result
	//	*AttachDriversFrame_Disconnect
	Body          isAttachDriversFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDriversFrame) Reset() {
	*x = AttachDriversFrame{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDriversFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDriversFrame) ProtoMessage() {}

func (x *AttachDriversFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDriversFrame.ProtoReflect.Descriptor instead.
func (*AttachDriversFrame) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AttachDriversFrame) GetBody() isAttachDriversFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AttachDriversFrame) GetInit() *AttachDriversInit {
	if x != nil {
		if x, ok := x.Body.(*AttachDriversFrame_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *AttachDriversFrame) GetDispatch() *DriverDispatchCall {
	if x != nil {
		if x, ok := x.Body.(*AttachDriversFrame_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *AttachDriversFrame) GetResult() *DriverDispatchResult {
	if x != nil {
		if x, ok := x.Body.(*AttachDriversFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AttachDriversFrame) GetDisconnect() *AgentDisconnect {
	if x != nil {
		if x, ok := x.Body.(*AttachDriversFrame_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isAttachDriversFrame_Body interface {
	isAttachDriversFrame_Body()
}

type AttachDriversFrame_Init struct {
	Init *AttachDriversInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type AttachDriversFrame_Dispatch struct {
	Dispatch *DriverDispatchCall `protobuf:"bytes,2,opt,name=dispatch,proto3,oneof"` // CP → agent
}

type AttachDriversFrame_Result struct {
	Result *DriverDispatchResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"` // agent → CP
}

type AttachDriversFrame_Disconnect struct {
	// disconnect frames close the stream cleanly. Either side
	// can send ; the other side acks then drops.
	Disconnect *AgentDisconnect `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"`
}

func (*AttachDriversFrame_Init) isAttachDriversFrame_Body() {}

func (*AttachDriversFrame_Dispatch) isAttachDriversFrame_Body() {}

func (*AttachDriversFrame_Result) isAttachDriversFrame_Body() {}

func (*AttachDriversFrame_Disconnect) isAttachDriversFrame_Body() {}

// DriverDispatchCall identifies which driver method on which
// driver kind the control plane wants the agent to invoke.
// The payload is opaque protobuf bytes — the agent decodes it
// against the per-method request type for the kind.
type DriverDispatchCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// call_id is a per-stream monotonic counter the agent echoes
	// back in DriverDispatchResult. Lets the CP correlate
	// concurrent calls on the same stream.
	CallId        uint64 `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	DriverKind    string `protobuf:"bytes,2,opt,name=driver_kind,json=driverKind,proto3" json:"driver_kind,omitempty"` // "hypervisor" | "network" | "volume" | "image"
	MethodName    string `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"` // "CreateVM" | "AttachPort" | "EnsureVolume" | …
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                         // marshalled per-method request proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDispatchCall) Reset() {
	*x = DriverDispatchCall{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDispatchCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDispatchCall) ProtoMessage() {}

func (x *DriverDispatchCall) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDispatchCall.ProtoReflect.Descriptor instead.
func (*DriverDispatchCall) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DriverDispatchCall) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *DriverDispatchCall) GetDriverKind() string {
	if x != nil {
		return x.DriverKind
	}
	return ""
}

func (x *DriverDispatchCall) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *DriverDispatchCall) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DriverDispatchResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId uint64                 `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Exactly one of {payload, error_message} is set.
	Payload      []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // marshalled per-method response proto
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// error_kind helps the caller distinguish driver-typed
	// errors from transport errors. Empty when no error.
	ErrorKind     string `protobuf:"bytes,4,opt,name=error_kind,json=errorKind,proto3" json:"error_kind,omitempty"` // "" | "unsupported" | "not_applicable" | "not_found" | "internal"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDispatchResult) Reset() {
	*x = DriverDispatchResult{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDispatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDispatchResult) ProtoMessage() {}

func (x *DriverDispatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDispatchResult.ProtoReflect.Descriptor instead.
func (*DriverDispatchResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DriverDispatchResult) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *DriverDispatchResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DriverDispatchResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DriverDispatchResult) GetErrorKind() string {
	if x != nil {
		return x.ErrorKind
	}
	return ""
}

type AgentDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDisconnect) Reset() {
	*x = AgentDisconnect{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDisconnect) ProtoMessage() {}

func (x *AgentDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDisconnect.ProtoReflect.Descriptor instead.
func (*AgentDisconnect) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentDisconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\rweft.agent.v1\x1a\n" +
	"weft.proto\"\xea\x06\n" +
	"\x10HostRegistration\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02az\x18\x03 \x01(\tR\x02az\x12\x12\n" +
	"\x04rack\x18\x04 \x01(\tR\x04rack\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x1e\n" +
	"\n" +
	"hypervisor\x18\x06 \x01(\tR\n" +
	"hypervisor\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x12#\n" +
	"\rnetwork_types\x18\b \x03(\tR\fnetworkTypes\x12'\n" +
	"\x0fvolume_backends\x18\t \x03(\tR\x0evolumeBackends\x12O\n" +
	"\n" +
	"properties\x18\n" +
	" \x03(\v2/.weft.agent.v1.HostRegistration.PropertiesEntryR\n" +
	"properties\x12#\n" +
	"\ragent_version\x18\v \x01(\tR\fagentVersion\x12\\\n" +
	"\x0fdriver_versions\x18\f \x03(\v23.weft.agent.v1.HostRegistration.DriverVersionsEntryR\x0edriverVersions\x12\x13\n" +
	"\x05os_id\x18\r \x01(\tR\x04osId\x12\x1d\n" +
	"\n" +
	"os_version\x18\x0e \x01(\tR\tosVersion\x12\x1b\n" +
	"\tos_pretty\x18\x0f \x01(\tR\bosPretty\x12%\n" +
	"\x0ekernel_version\x18\x10 \x01(\tR\rkernelVersion\x12H\n" +
	"\x12network_interfaces\x18\x11 \x03(\v2\x19.weft.v1.NetworkInterfaceR\x11networkInterfaces\x12<\n" +
	"\x0estorage_mounts\x18\x12 \x03(\v2\x15.weft.v1.StorageMountR\rstorageMounts\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13DriverVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x14RegisterAgentRequest\x12C\n" +
	"\fregistration\x18\x01 \x01(\v2\x1f.weft.agent.v1.HostRegistrationR\fregistration\"<\n" +
	"\x15RegisterAgentResponse\x12#\n" +
	"\rassigned_uuid\x18\x01 \x01(\tR\fassignedUuid\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\thost_uuid\x18\x01 \x01(\tR\bhostUuid\"\x13\n" +
	"\x11HeartbeatResponse\"S\n" +
	"\x11AttachDriversInit\x12\x1b\n" +
	"\thost_uuid\x18\x01 \x01(\tR\bhostUuid\x12!\n" +
	"\fdriver_kinds\x18\x02 \x03(\tR\vdriverKinds\"\x96\x02\n" +
	"\x12AttachDriversFrame\x126\n" +
	"\x04init\x18\x01 \x01(\v2 .weft.agent.v1.AttachDriversInitH\x00R\x04init\x12?\n" +
	"\bdispatch\x18\x02 \x01(\v2!.weft.agent.v1.DriverDispatchCallH\x00R\bdispatch\x12=\n" +
	"\x06result\x18\x03 \x01(\v2#.weft.agent.v1.DriverDispatchResultH\x00R\x06result\x12@\n" +
	"\n" +
	"disconnect\x18\x04 \x01(\v2\x1e.weft.agent.v1.AgentDisconnectH\x00R\n" +
	"disconnectB\x06\n" +
	"\x04body\"\x89\x01\n" +
	"\x12DriverDispatchCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x04R\x06callId\x12\x1f\n" +
	"\vdriver_kind\x18\x02 \x01(\tR\n" +
	"driverKind\x12\x1f\n" +
	"\vmethod_name\x18\x03 \x01(\tR\n" +
	"methodName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x8d\x01\n" +
	"\x14DriverDispatchResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x04R\x06callId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_kind\x18\x04 \x01(\tR\terrorKind\")\n" +
	"\x0fAgentDisconnect\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\x9a\x02\n" +
	"\x11AgentControlPlane\x12Z\n" +
	"\rRegisterAgent\x12#.weft.agent.v1.RegisterAgentRequest\x1a$.weft.agent.v1.RegisterAgentResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.weft.agent.v1.HeartbeatRequest\x1a .weft.agent.v1.HeartbeatResponse\x12Y\n" +
	"\rAttachDrivers\x12!.weft.agent.v1.AttachDriversFrame\x1a!.weft.agent.v1.AttachDriversFrame(\x010\x01B0Z.github.com/openweft/weft-proto/agentv1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(*HostRegistration)(nil),            // 0: weft.agent.v1.HostRegistration
	(*RegisterAgentRequest)(nil),        // 1: weft.agent.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),       // 2: weft.agent.v1.RegisterAgentResponse
	(*HeartbeatRequest)(nil),            // 3: weft.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 4: weft.agent.v1.HeartbeatResponse
	(*AttachDriversInit)(nil),           // 5: weft.agent.v1.AttachDriversInit
	(*AttachDriversFrame)(nil),          // 6: weft.agent.v1.AttachDriversFrame
	(*DriverDispatchCall)(nil),          // 7: weft.agent.v1.DriverDispatchCall
	(*DriverDispatchResult)(nil),        // 8: weft.agent.v1.DriverDispatchResult
	(*AgentDisconnect)(nil),             // 9: weft.agent.v1.AgentDisconnect
	nil,                                 // 10: weft.agent.v1.HostRegistration.PropertiesEntry
	nil,                                 // 11: weft.agent.v1.HostRegistration.DriverVersionsEntry
	(*weft_proto.NetworkInterface)(nil), // 12: weft.v1.NetworkInterface
	(*weft_proto.StorageMount)(nil),     // 13: weft.v1.StorageMount
}
var file_agent_proto_depIdxs = []int32{
	10, // 0: weft.agent.v1.HostRegistration.properties:type_name -> weft.agent.v1.HostRegistration.PropertiesEntry
	11, // 1: weft.agent.v1.HostRegistration.driver_versions:type_name -> weft.agent.v1.HostRegistration.DriverVersionsEntry
	12, // 2: weft.agent.v1.HostRegistration.network_interfaces:type_name -> weft.v1.NetworkInterface
	13, // 3: weft.agent.v1.HostRegistration.storage_mounts:type_name -> weft.v1.StorageMount
	0,  // 4: weft.agent.v1.RegisterAgentRequest.registration:type_name -> weft.agent.v1.HostRegistration
	5,  // 5: weft.agent.v1.AttachDriversFrame.init:type_name -> weft.agent.v1.AttachDriversInit
	7,  // 6: weft.agent.v1.AttachDriversFrame.dispatch:type_name -> weft.agent.v1.DriverDispatchCall
	8,  // 7: weft.agent.v1.AttachDriversFrame.result:type_name -> weft.agent.v1.DriverDispatchResult
	9,  // 8: weft.agent.v1.AttachDriversFrame.disconnect:type_name -> weft.agent.v1.AgentDisconnect
	1,  // 9: weft.agent.v1.AgentControlPlane.RegisterAgent:input_type -> weft.agent.v1.RegisterAgentRequest
	3,  // 10: weft.agent.v1.AgentControlPlane.Heartbeat:input_type -> weft.agent.v1.HeartbeatRequest
	6,  // 11: weft.agent.v1.AgentControlPlane.AttachDrivers:input_type -> weft.agent.v1.AttachDriversFrame
	2,  // 12: weft.agent.v1.AgentControlPlane.RegisterAgent:output_type -> weft.agent.v1.RegisterAgentResponse
	4,  // 13: weft.agent.v1.AgentControlPlane.Heartbeat:output_type -> weft.agent.v1.HeartbeatResponse
	6,  // 14: weft.agent.v1.AgentControlPlane.AttachDrivers:output_type -> weft.agent.v1.AttachDriversFrame
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*AttachDriversFrame_Init)(nil),
		(*AttachDriversFrame_Dispatch)(nil),
		(*AttachDriversFrame_Result)(nil),
		(*AttachDriversFrame_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
