// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: agent.proto

// agent.proto defines the control-plane ↔ agent transport. One
// `AgentControlPlane` service that the agent dials at startup ;
// one `AttachDrivers` bidirectional stream the control plane
// uses to dispatch driver calls (Hypervisor / Network / Volume
// / Image) back into the agent.
//
// Why a separate file from weft.proto:
//
//   * `WeftService` is the public operator API (CLI, dashboard,
//     terraform-provider). It carries operator-side
//     RegisterHost/Heartbeat too — but those are operator
//     intent, surfaced under operator auth.
//   * `AgentControlPlane` is internal traffic, machine-to-
//     machine, with agent-identity auth (mTLS client cert, in
//     the simplest setup). Keeping it in its own .proto file +
//     its own service name makes the security policy easy to
//     state ("operators don't speak AgentControlPlane ; only
//     weft-agents do").
//
// See [[openweft-module-layout]] for the broader naming map and
// [[weft-driver-registry-split]] for why each driver type
// surfaces here individually.

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlPlane_RegisterAgent_FullMethodName = "/weft.agent.v1.AgentControlPlane/RegisterAgent"
	AgentControlPlane_Heartbeat_FullMethodName     = "/weft.agent.v1.AgentControlPlane/Heartbeat"
	AgentControlPlane_AttachDrivers_FullMethodName = "/weft.agent.v1.AgentControlPlane/AttachDrivers"
)

// AgentControlPlaneClient is the client API for AgentControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlPlaneClient interface {
	// RegisterAgent + Heartbeat are the lifecycle calls. Unary
	// RPCs because they're rare + need explicit success/failure.
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// AttachDrivers is the long-lived bidi stream the CP uses to
	// dispatch driver calls. Agent → first frame is the init
	// message ; after that, the stream is fully bidi.
	AttachDrivers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachDriversFrame, AttachDriversFrame], error)
}

type agentControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlPlaneClient(cc grpc.ClientConnInterface) AgentControlPlaneClient {
	return &agentControlPlaneClient{cc}
}

func (c *agentControlPlaneClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, AgentControlPlane_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneClient) AttachDrivers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachDriversFrame, AttachDriversFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlPlane_ServiceDesc.Streams[0], AgentControlPlane_AttachDrivers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachDriversFrame, AttachDriversFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlane_AttachDriversClient = grpc.BidiStreamingClient[AttachDriversFrame, AttachDriversFrame]

// AgentControlPlaneServer is the server API for AgentControlPlane service.
// All implementations must embed UnimplementedAgentControlPlaneServer
// for forward compatibility.
type AgentControlPlaneServer interface {
	// RegisterAgent + Heartbeat are the lifecycle calls. Unary
	// RPCs because they're rare + need explicit success/failure.
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// AttachDrivers is the long-lived bidi stream the CP uses to
	// dispatch driver calls. Agent → first frame is the init
	// message ; after that, the stream is fully bidi.
	AttachDrivers(grpc.BidiStreamingServer[AttachDriversFrame, AttachDriversFrame]) error
	mustEmbedUnimplementedAgentControlPlaneServer()
}

// UnimplementedAgentControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlPlaneServer struct{}

func (UnimplementedAgentControlPlaneServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentControlPlaneServer) AttachDrivers(grpc.BidiStreamingServer[AttachDriversFrame, AttachDriversFrame]) error {
	return status.Error(codes.Unimplemented, "method AttachDrivers not implemented")
}
func (UnimplementedAgentControlPlaneServer) mustEmbedUnimplementedAgentControlPlaneServer() {}
func (UnimplementedAgentControlPlaneServer) testEmbeddedByValue()                           {}

// UnsafeAgentControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlPlaneServer will
// result in compilation errors.
type UnsafeAgentControlPlaneServer interface {
	mustEmbedUnimplementedAgentControlPlaneServer()
}

func RegisterAgentControlPlaneServer(s grpc.ServiceRegistrar, srv AgentControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedAgentControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlPlane_ServiceDesc, srv)
}

func _AgentControlPlane_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlane_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlane_AttachDrivers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlPlaneServer).AttachDrivers(&grpc.GenericServerStream[AttachDriversFrame, AttachDriversFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlane_AttachDriversServer = grpc.BidiStreamingServer[AttachDriversFrame, AttachDriversFrame]

// AgentControlPlane_ServiceDesc is the grpc.ServiceDesc for AgentControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.agent.v1.AgentControlPlane",
	HandlerType: (*AgentControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentControlPlane_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentControlPlane_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachDrivers",
			Handler:       _AgentControlPlane_AttachDrivers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
